# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bbc113aea9d438586329ce99bec56866"
name = "mono-subscription"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_orders,read_products,write_products,read_customers,write_app_proxy"

[app_proxy]
url = "https://lindsay-figure-mill-informative.trycloudflare.com/mono"
prefix = "apps"
subpath = "mono"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth", "https://lindsay-figure-mill-informative.trycloudflare.com/auth/callback" ]
