# Learn more about configuring your Customer account UI extension:
# https://shopify.dev/api/customer-account-ui-extensions/unstable/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2025-07"

[[extensions]]
name = "order-status-page"
handle = "order-status-page"
type = "ui_extension"
uid = "ff517eb0-2b0b-ff40-bfae-1c2442e8420e7ad791bb"

# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/customer-account-ui-extensions/unstable/extension-targets-overview

[[extensions.targeting]]
module = "./src/OrderStatusBlock.jsx"
target = "customer-account.order-status.block.render"

[extensions.capabilities]
# Gives your extension access to directly query Shopify’s storefront API.
# https://shopify.dev/docs/api/customer-account-ui-extensions/unstable/configuration#api-access
api_access = true
network_access = true

[[extensions.settings.fields]]
key = "mono_subscription_gateway"
type = "single_line_text_field"
name = "Назва шлюзу"
description = "Назва шлюзу для Підписки від Монобанку"

